name: Pylint Check

on:
  push:
    branches:
      - main
      - master

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install pylint

    - name: Determine changed Python files
      id: changed_files
      run: |
        echo "::set-output name=python_files::$(git diff --name-only --diff-filter=AM -- '*.py')"
      shell: bash

    - name: Run Pylint on changed files
      run: |
        if [[ -n "${{ steps.changed_files.outputs.python_files }}" ]]; then
          pylint --output-format=text ${{ steps.changed_files.outputs.python_files }} > pylint-report.txt
        fi
      shell: bash

    - name: Upload Pylint report
      uses: actions/upload-artifact@v3
      with:
        name: pylint-report
        path: pylint-report.txt
